<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AdminProfileSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('admin_profiles')->insert([
            [
                'admin_id' => 1,
                'lastname' => '栫',
                'firstname' => '勝宏',
                'lastname_kana' => 'カコイ',
                'firstname_kana' => 'カツヒロ',
                'admin_photo_path' => null,
                'birth' => '1981-12-15',
                'gender' => '男性',
                'mobile_number' => '090-9580-9257',
                'admin_no' => 'KATSUCODE-0001',
                'serial_no' => null,
                'website' => 'https://katsucode.jp',
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'line' => null,
            ],
            [
                'admin_id' => 2,
                'lastname' => '中村',
                'firstname' => '英俊',
                'lastname_kana' => 'ナカムラ',
                'firstname_kana' => 'ヒデトシ',
                'admin_photo_path' => null,
                'birth' => '1985-12-15',
                'gender' => '男性',
                'mobile_number' => '090-9580-9257',
                'admin_no' => 'KENKOSYA-0001',
                'serial_no' => null,
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'line' => null,
            ],
            [
                'admin_id' => 3,
                'lastname' => '近藤',
                'firstname' => '太郎',
                'lastname_kana' => 'カコイ',
                'firstname_kana' => 'タロウ',
                'admin_photo_path' => null,
                'birth' => '1985-12-15',
                'gender' => '男性',
                'mobile_number' => '090-9580-9257',
                'admin_no' => 'KENKOSYA-0002',
                'serial_no' => null,
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'line' => null,
            ],
            [
                'admin_id' => 4,
                'lastname' => '近藤',
                'firstname' => '太郎',
                'lastname_kana' => 'カコイ',
                'firstname_kana' => 'タロウ',
                'admin_photo_path' => null,
                'birth' => '1985-12-15',
                'gender' => '男性',
                'mobile_number' => '090-9580-9257',
                'admin_no' => 'KENKOSYA-0003',
                'serial_no' => null,
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'line' => null,
            ],
            [
                'admin_id' => 5,
                'lastname' => '大谷',
                'firstname' => '花子',
                'lastname_kana' => 'オオタニ',
                'firstname_kana' => 'ハナコ',
                'admin_photo_path' => null,
                'birth' => '1985-12-15',
                'gender' => '女性',
                'mobile_number' => '090-9580-9257',
                'admin_no' => 'KENKOSYA-0004',
                'serial_no' => null,
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'line' => null,
            ],
            [
                'admin_id' => 6,
                'lastname' => '大谷',
                'firstname' => '花子',
                'lastname_kana' => 'オオタニ',
                'firstname_kana' => 'ハナコ',
                'admin_photo_path' => null,
                'birth' => '1985-12-15',
                'gender' => '女性',
                'mobile_number' => '090-9580-9257',
                'admin_no' => 'KENKOSYA-0005',
                'serial_no' => null,
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'line' => null,
            ],
            [
                'admin_id' => 7,
                'lastname' => '中村',
                'firstname' => '周平',
                'lastname_kana' => 'ナカムラ',
                'firstname_kana' => 'シュウヘイ',
                'admin_photo_path' => null,
                'birth' => '1985-12-15',
                'gender' => '男性',
                'mobile_number' => '090-9580-9257',
                'admin_no' => 'SHUPLAY-0001',
                'serial_no' => null,
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'line' => null,
            ],
            [
                'admin_id' => 8,
                'lastname' => '相賀',
                'firstname' => '高揚',
                'lastname_kana' => 'アイガ',
                'firstname_kana' => 'コウヨウ',
                'admin_photo_path' => null,
                'birth' => '1985-12-15',
                'gender' => '男性',
                'mobile_number' => '090-9580-9257',
                'admin_no' => 'SHUPLAY-0002',
                'serial_no' => null,
                'website' => null,
                'facebook' => null,
                'twitter' => null,
                'instagram' => null,
                'youtube' => null,
                'line' => null,
            ],
        ]);
    }
}
