<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CourseCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('course_categories')->insert([
            [
                'lesson_id' => 1,
                'type' => '一般教室',
                'name' => '一般教室',
                'description' => '一般会員向け体操教室の説明',
                'course_category_photo_path' => null,
                'status' => true,
                'start_date' => '2023-05-01',
                'end_date' => null,
                'created_at' => '2023-05-01',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 1,
                'type' => '体験教室',
                'name' => '無料体験教室',
                'description' => '非会員向け無料体操教室の説明',
                'course_category_photo_path' => null,
                'status' => true,
                'start_date' => '2023-05-01',
                'end_date' => null,
                'created_at' => '2023-05-01',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 1,
                'type' => '体験教室',
                'name' => '有料体験教室',
                'description' => '非会員向け有料体操教室の説明',
                'course_category_photo_path' => null,
                'status' => true,
                'start_date' => '2023-05-01',
                'end_date' => null,
                'created_at' => '2023-05-01',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 1,
                'type' => '体験教室',
                'name' => '2023夏の体験教室',
                'description' => '2023年夏の体験教室の説明',
                'course_category_photo_path' => null,
                'status' => false,
                'start_date' => '2023-07-20',
                'end_date' => '2023-08-31',
                'created_at' => '2023-06-20',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 1,
                'type' => '体験教室',
                'name' => '2023冬の体験教室',
                'description' => '2023年冬の体験教室の説明',
                'course_category_photo_path' => null,
                'status' => false,
                'start_date' => '2023-12-20',
                'end_date' => '2024-01-10',
                'created_at' => '2023-11-20',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 1,
                'type' => '短期教室',
                'name' => '2023冬の短期教室',
                'description' => '2023年冬の短期教室の説明',
                'course_category_photo_path' => null,
                'status' => false,
                'start_date' => '2023-12-20',
                'end_date' => '2024-01-10',
                'created_at' => '2023-11-20',
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 1,
                'type' => '体験教室',
                'name' => '2024夏の体験教室',
                'description' => '2024年夏の体験教室の説明',
                'course_category_photo_path' => null,
                'status' => false,
                'start_date' => '2024-07-20',
                'end_date' => '2024-08-31',
                'created_at' => '2024-06-20',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 1,
                'type' => '短期教室',
                'name' => '2024夏の短期教室',
                'description' => '2024年夏の短期教室の説明',
                'course_category_photo_path' => null,
                'status' => false,
                'start_date' => '2024-07-20',
                'end_date' => '2024-08-31',
                'created_at' => '2024-06-20',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 1,
                'type' => '体験教室',
                'name' => '2024冬の短期教室',
                'description' => '2024年冬の体験教室の説明',
                'course_category_photo_path' => null,
                'status' => false,
                'start_date' => '2024-12-20',
                'end_date' => '2025-01-10',
                'created_at' => '2024-11-20',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 1,
                'type' => '短期教室',
                'name' => '2024冬の短期教室',
                'description' => '2024年冬の短期教室の説明',
                'course_category_photo_path' => null,
                'status' => false,
                'start_date' => '2024-12-20',
                'end_date' => '2025-01-10',
                'created_at' => '2024-11-20',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 1,
                'type' => '体験教室',
                'name' => '2025春の短期教室',
                'description' => '2025年春の体験教室の説明',
                'course_category_photo_path' => null,
                'status' => false,
                'start_date' => '2025-04-01',
                'end_date' => '2025-04-10',
                'created_at' => '2024-03-01',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 1,
                'type' => '短期教室',
                'name' => '2025春の短期教室',
                'description' => '2025年春の短期教室の説明',
                'course_category_photo_path' => null,
                'status' => false,
                'start_date' => '2025-04-01',
                'end_date' => '2025-04-10',
                'created_at' => '2024-03-01',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 2,
                'type' => '一般教室',
                'name' => '一般教室',
                'description' => '一般会員向けヨガ教室の説明',
                'course_category_photo_path' => null,
                'status' => true,
                'start_date' => '2024-09-01',
                'end_date' => null,
                'created_at' => '2024-09-01',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 2,
                'type' => '体験教室',
                'name' => '無料体験教室',
                'description' => '非会員向け無料ヨガ教室の説明',
                'course_category_photo_path' => null,
                'status' => true,
                'start_date' => '2024-09-01',
                'end_date' => null,
                'created_at' => '2024-09-01',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 2,
                'type' => '体験教室',
                'name' => '有料体験教室',
                'description' => '非会員向け有料ヨガ教室の説明',
                'course_category_photo_path' => null,
                'status' => true,
                'start_date' => '2024-09-01',
                'end_date' => null,
                'created_at' => '2024-09-01',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 3,
                'type' => '一般教室',
                'name' => '一般教室',
                'description' => '一般会員向けピラティス教室の説明',
                'course_category_photo_path' => null,
                'status' => true,
                'start_date' => '2024-09-01',
                'end_date' => null,
                'created_at' => '2024-09-01',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 3,
                'type' => '体験教室',
                'name' => '無料体験教室',
                'description' => '非会員向け無料ピラティス教室の説明',
                'course_category_photo_path' => null,
                'status' => true,
                'start_date' => '2024-09-01',
                'end_date' => null,
                'created_at' => '2024-09-01',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 3,
                'type' => '体験教室',
                'name' => '有料体験教室',
                'description' => '非会員向け有料ピラティス教室の説明',
                'course_category_photo_path' => null,
                'status' => true,
                'start_date' => '2024-09-01',
                'end_date' => null,
                'created_at' => '2024-09-01',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 4,
                'type' => '一般教室',
                'name' => '一般教室',
                'description' => '一般会員向けプログラミング教室の説明',
                'course_category_photo_path' => null,
                'status' => true,
                'start_date' => '2024-09-01',
                'end_date' => null,
                'created_at' => '2024-09-01',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 4,
                'type' => '体験教室',
                'name' => '無料体験教室',
                'description' => '非会員向け無料プログラミング教室の説明',
                'course_category_photo_path' => null,
                'status' => true,
                'start_date' => '2024-09-01',
                'end_date' => null,
                'created_at' => '2024-09-01',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 4,
                'type' => '体験教室',
                'name' => '有料体験教室',
                'description' => '非会員向け有料プログラミング教室の説明',
                'course_category_photo_path' => null,
                'status' => true,
                'start_date' => '2024-09-01',
                'end_date' => null,
                'created_at' => '2024-09-01',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 5,
                'type' => '一般教室',
                'name' => '一般教室',
                'description' => '一般会員向けゲーミング教室の説明',
                'course_category_photo_path' => null,
                'status' => true,
                'start_date' => '2024-09-01',
                'end_date' => null,
                'created_at' => '2024-09-01',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 5,
                'type' => '体験教室',
                'name' => '無料体験教室',
                'description' => '非会員向け無料ゲーミング教室の説明',
                'course_category_photo_path' => null,
                'status' => true,
                'start_date' => '2024-09-01',
                'end_date' => null,
                'created_at' => '2024-09-01',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 5,
                'type' => '体験教室',
                'name' => '有料体験教室',
                'description' => '非会員向け有料ゲーミング教室の説明',
                'course_category_photo_path' => null,
                'status' => true,
                'start_date' => '2024-09-01',
                'end_date' => null,
                'created_at' => '2024-09-01',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 6,
                'type' => '一般教室',
                'name' => '一般教室',
                'description' => '一般会員向けピアノ教室の説明',
                'course_category_photo_path' => null,
                'status' => true,
                'start_date' => '2024-09-01',
                'end_date' => null,
                'created_at' => '2024-09-01',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 6,
                'type' => '体験教室',
                'name' => '無料体験教室',
                'description' => '非会員向け無料ピアノ教室の説明',
                'course_category_photo_path' => null,
                'status' => true,
                'start_date' => '2024-09-01',
                'end_date' => null,
                'created_at' => '2024-09-01',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 6,
                'type' => '体験教室',
                'name' => '有料体験教室',
                'description' => '非会員向け有料ピアノ教室の説明',
                'course_category_photo_path' => null,
                'status' => true,
                'start_date' => '2024-09-01',
                'end_date' => null,
                'created_at' => '2024-09-01',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 7,
                'type' => '一般教室',
                'name' => '一般教室',
                'description' => '一般会員向けバイオリン教室の説明',
                'course_category_photo_path' => null,
                'status' => true,
                'start_date' => '2024-09-01',
                'end_date' => null,
                'created_at' => '2024-09-01',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 7,
                'type' => '体験教室',
                'name' => '無料体験教室',
                'description' => '非会員向け無料バイオリン教室の説明',
                'course_category_photo_path' => null,
                'status' => true,
                'start_date' => '2024-09-01',
                'end_date' => null,
                'created_at' => '2024-09-01',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 7,
                'type' => '体験教室',
                'name' => '有料体験教室',
                'description' => '非会員向け有料バイオリン教室の説明',
                'course_category_photo_path' => null,
                'status' => true,
                'start_date' => '2024-09-01',
                'end_date' => null,
                'created_at' => '2024-09-01',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 8,
                'type' => '一般教室',
                'name' => '一般教室',
                'description' => '一般会員向けギター教室の説明',
                'course_category_photo_path' => null,
                'status' => true,
                'start_date' => '2024-09-01',
                'end_date' => null,
                'created_at' => '2024-09-01',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 8,
                'type' => '体験教室',
                'name' => '無料体験教室',
                'description' => '非会員向け無料ギター教室の説明',
                'course_category_photo_path' => null,
                'status' => true,
                'start_date' => '2024-09-01',
                'end_date' => null,
                'created_at' => '2024-09-01',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 8,
                'type' => '体験教室',
                'name' => '有料体験教室',
                'description' => '非会員向け有料ギター教室の説明',
                'course_category_photo_path' => null,
                'status' => true,
                'start_date' => '2024-09-01',
                'end_date' => null,
                'created_at' => '2024-09-01',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 9,
                'type' => '一般教室',
                'name' => '一般教室',
                'description' => '一般会員向けドラム教室の説明',
                'course_category_photo_path' => null,
                'status' => true,
                'start_date' => '2024-09-01',
                'end_date' => null,
                'created_at' => '2024-09-01',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 9,
                'type' => '体験教室',
                'name' => '無料体験教室',
                'description' => '非会員向け無料ドラム教室の説明',
                'course_category_photo_path' => null,
                'status' => true,
                'start_date' => '2024-09-01',
                'end_date' => null,
                'created_at' => '2024-09-01',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 9,
                'type' => '体験教室',
                'name' => '有料体験教室',
                'description' => '非会員向け有料ドラム教室の説明',
                'course_category_photo_path' => null,
                'status' => true,
                'start_date' => '2024-09-01',
                'end_date' => null,
                'created_at' => '2024-09-01',
                'updated_at' => null,
                'deleted_at' => null,
            ],

            [
                'lesson_id' => 10,
                'type' => '一般教室',
                'name' => '一般教室',
                'description' => '一般会員向けボーカル教室の説明',
                'course_category_photo_path' => null,
                'status' => true,
                'start_date' => '2024-09-01',
                'end_date' => null,
                'created_at' => '2024-09-01',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 10,
                'type' => '体験教室',
                'name' => '無料体験教室',
                'description' => '非会員向け無料ボーカル教室の説明',
                'course_category_photo_path' => null,
                'status' => true,
                'start_date' => '2024-09-01',
                'end_date' => null,
                'created_at' => '2024-09-01',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 10,
                'type' => '体験教室',
                'name' => '有料体験教室',
                'description' => '非会員向け有料ボーカル教室の説明',
                'course_category_photo_path' => null,
                'status' => true,
                'start_date' => '2024-09-01',
                'end_date' => null,
                'created_at' => '2024-09-01',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 11,
                'type' => '一般教室',
                'name' => '一般教室',
                'description' => '一般会員向け水泳教室の説明',
                'course_category_photo_path' => null,
                'status' => true,
                'start_date' => '2025-04-01',
                'end_date' => null,
                'created_at' => '2025-03-01',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 11,
                'type' => '体験教室',
                'name' => '無料体験教室',
                'description' => '非会員向け無料水泳教室の説明',
                'course_category_photo_path' => null,
                'status' => true,
                'start_date' => '2025-04-01',
                'end_date' => null,
                'created_at' => '2025-03-01',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'lesson_id' => 11,
                'type' => '体験教室',
                'name' => '有料体験教室',
                'description' => '非会員向け有料水泳教室の説明',
                'course_category_photo_path' => null,
                'status' => true,
                'start_date' => '2025-04-01',
                'end_date' => null,
                'created_at' => '2025-03-01',
                'updated_at' => null,
                'deleted_at' => null,
            ],
        ]);
    }
}
