<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EventSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('events')->insert([
            [
                'name' => '2023年ハローウィンパーティー',
                'description' => '2023年のハローウィンパーティーを開催します！',
                'event_photo_path' => null,
                'postalcode' => '6610976',
                'prefecture' => '兵庫県',
                'city' => '尼崎市',
                'address1' => '潮江',
                'address2' => '1丁目16番1号 アミング潮江ウエスト二番館201-6',
                'phone_number' => '0649506939',
                'status' => 1,
                'event_start_date' => '2023-10-31',
                'event_end_date' => '2023-10-31',
                'application_start_date' => '2023-10-01',
                'application_start_time' => '10:00:00',
                'application_end_date' => '2023-10-30',
                'application_end_time' => '18:00:00',
            ],
            [
                'name' => '2023年クリスマスパーティー',
                'description' => '2023年のクリスマスパーティーを開催します！',
                'event_photo_path' => null,
                'postalcode' => '6610976',
                'prefecture' => '兵庫県',
                'city' => '尼崎市',
                'address1' => '潮江',
                'address2' => '1丁目16番1号 アミング潮江ウエスト二番館201-6',
                'phone_number' => '0649506939',
                'status' => 1,
                'event_start_date' => '2023-12-25',
                'event_end_date' => '2023-12-25',
                'application_start_date' => '2023-12-01',
                'application_start_time' => '10:00:00',
                'application_end_date' => '2023-12-24',
                'application_end_time' => '18:00:00',
            ],
            [
                'name' => '2024年新年会',
                'description' => '2024年の新年会を開催します！',
                'event_photo_path' => null,
                'postalcode' => '6610976',
                'prefecture' => '兵庫県',
                'city' => '尼崎市',
                'address1' => '潮江',
                'address2' => '1丁目16番1号 アミング潮江ウエスト二番館201-6',
                'phone_number' => '0649506939',
                'status' => 1,
                'event_start_date' => '2024-01-01',
                'event_end_date' => '2024-01-01',
                'application_start_date' => '2023-12-15',
                'application_start_time' => '10:00:00',
                'application_end_date' => '2023-12-31',
                'application_end_time' => '18:00:00',
            ],
            [
                'name' => '2024年春の体操教室',
                'description' => '2024年の春に体操教室を開催します！',
                'event_photo_path' => null,
                'postalcode' => '6610976',
                'prefecture' => '兵庫県',
                'city' => '尼崎市',
                'address1' => '潮江',
                'address2' => '1丁目16番1号 アミング潮江ウエスト二番館201-6',
                'phone_number' => '0649506939',
                'status' => 1,
                'event_start_date' => '2024-04-01',
                'event_end_date' => '2024-04-30',
                'application_start_date' => '2024-03-01',
                'application_start_time' => '10:00:00',
                'application_end_date' => '2024-03-31',
                'application_end_time' => '18:00:00',
            ],
            [
                'name' => '2024年夏の音楽フェスティバル',
                'description' => '2024年の夏に音楽フェスティバルを開催します！',
                'event_photo_path' => null,
                'postalcode' => '6610976',
                'prefecture' => '兵庫県',
                'city' => '尼崎市',
                'address1' => '潮江',
                'address2' => '1丁目16番1号 アミング潮江ウエスト二番館201-6',
                'phone_number' => '0649506939',
                'status' => 1,
                'event_start_date' => '2024-07-01',
                'event_end_date' => '2024-07-31',
                'application_start_date' => '2024-06-01',
                'application_start_time' => '10:00:00',
                'application_end_date' => '2024-06-30',
                'application_end_time' => '18:00:00',
            ],
            [
                'name' => '2024年秋の文化祭',
                'description' => '2024年の秋に文化祭を開催します！',
                'event_photo_path' => null,
                'postalcode' => '6610976',
                'prefecture' => '兵庫県',
                'city' => '尼崎市',
                'address1' => '潮江',
                'address2' => '1丁目16番1号 アミング潮江ウエスト二番館201-6',
                'phone_number' => '0649506939',
                'status' => 1,
                'event_start_date' => '2024-10-01',
                'event_end_date' => '2024-10-31',
                'application_start_date' => '2024-09-01',
                'application_start_time' => '10:00:00',
                'application_end_date' => '2024-09-30',
                'application_end_time' => '18:00:00',
            ],
            [
                'name' => '2025年冬のスポーツ大会',
                'description' => '2025年の冬にスポーツ大会を開催します！',
                'event_photo_path' => null,
                'postalcode' => '6610976',
                'prefecture' => '兵庫県',
                'city' => '尼崎市',
                'address1' => '潮江',
                'address2' => '1丁目16番1号 アミング潮江ウエスト二番館201-6',
                'phone_number' => '0649506939',
                'status' => 1,
                'event_start_date' => '2025-01-01',
                'event_end_date' => '2025-01-31',
                'application_start_date' => '2024-12-01',
                'application_start_time' => '10:00:00',
                'application_end_date' => '2024-12-31',
                'application_end_time' => '18:00:00',
            ],
            [
                'name' => '2025年春のダンスコンテスト',
                'description' => '2025年の春にダンスコンテストを開催します！',
                'event_photo_path' => null,
                'postalcode' => '6610976',
                'prefecture' => '兵庫県',
                'city' => '尼崎市',
                'address1' => '潮江',
                'address2' => '1丁目16番1号 アミング潮江ウエスト二番館201-6',
                'phone_number' => '0649506939',
                'status' => 1,
                'event_start_date' => '2025-04-01',
                'event_end_date' => '2025-04-30',
                'application_start_date' => '2025-03-01',
                'application_start_time' => '10:00:00',
                'application_end_date' => '2025-03-31',
                'application_end_time' => '18:00:00',
            ],
            [
                'name' => '2025年夏のアートフェスティバル',
                'description' => '2025年の夏にアートフェスティバルを開催します！',
                'event_photo_path' => null,
                'postalcode' => '6610976',
                'prefecture' => '兵庫県',
                'city' => '尼崎市',
                'address1' => '潮江',
                'address2' => '1丁目16番1号 アミング潮江ウエスト二番館201-6',
                'phone_number' => '0649506939',
                'status' => 1,
                'event_start_date' => '2025-07-01',
                'event_end_date' => '2025-07-31',
                'application_start_date' => '2025-06-01',
                'application_start_time' => '10:00:00',
                'application_end_date' => '2025-06-30',
                'application_end_time' => '18:00:00',
            ],
            [
                'name' => '2025年秋の音楽祭',
                'description' => '2025年の秋に音楽祭を開催します！',
                'event_photo_path' => null,
                'postalcode' => '6610976',
                'prefecture' => '兵庫県',
                'city' => '尼崎市',
                'address1' => '潮江',
                'address2' => '1丁目16番1号 アミング潮江ウエスト二番館201-6',
                'phone_number' => '0649506939',
                'status' => 1,
                'event_start_date' => '2025-10-01',
                'event_end_date' => '2025-10-31',
                'application_start_date' => '2025-09-01',
                'application_start_time' => '10:00:00',
                'application_end_date' => '2025-09-30',
                'application_end_time' => '18:00:00',
            ],
            [
                'name' => '2026年冬のファッションショー',
                'description' => '2026年の冬にファッションショーを開催します！',
                'event_photo_path' => null,
                'postalcode' => '6610976',
                'prefecture' => '兵庫県',
                'city' => '尼崎市',
                'address1' => '潮江',
                'address2' => '1丁目16番1号 アミング潮江ウエスト二番館201-6',
                'phone_number' => '0649506939',
                'status' => 1,
                'event_start_date' => '2026-01-01',
                'event_end_date' => '2026-01-31',
                'application_start_date' => '2025-12-01',
                'application_start_time' => '10:00:00',
                'application_end_date' => '2025-12-31',
                'application_end_time' => '18:00:00',
            ],
        ]);
    }
}
