<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StoreScheduleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('store_schedules')->insert([
            [
                'store_id' => 1,
                'business_date' => '2025-04-01',
                'start_time' => '11:00:00',
                'end_time' => '20:00:00',
                'day_of_week' => '火曜日',
                'status' => true,
                'note' => null,
            ],
            [
                'store_id' => 1,
                'business_date' => '2025-04-02',
                'start_time' => '11:00:00',
                'end_time' => '20:00:00',
                'day_of_week' => '水曜日',
                'status' => true,
                'note' => null,
            ],
            [
                'store_id' => 1,
                'business_date' => '2025-04-03',
                'start_time' => null,
                'end_time' => null,
                'day_of_week' => '木曜日',
                'status' => false,
                'note' => null,
            ],
            [
                'store_id' => 1,
                'business_date' => '2025-04-04',
                'start_time' => '11:00:00',
                'end_time' => '20:00:00',
                'day_of_week' => '金曜日',
                'status' => true,
                'note' => null,
            ],
            [
                'store_id' => 1,
                'business_date' => '2025-04-05',
                'start_time' => '08:00:00',
                'end_time' => '20:00:00',
                'day_of_week' => '土曜日',
                'status' => true,
                'note' => null,
            ],
            [
                'store_id' => 1,
                'business_date' => '2025-04-06',
                'start_time' => null,
                'end_time' => null,
                'day_of_week' => '日曜日',
                'status' => false,
                'note' => null,
            ],
            [
                'store_id' => 1,
                'business_date' => '2025-04-07',
                'start_time' => '11:00:00',
                'end_time' => '20:00:00',
                'day_of_week' => '月曜日',
                'status' => true,
                'note' => null,
            ],
            [
                'store_id' => 1,
                'business_date' => '2025-04-08',
                'start_time' => '11:00:00',
                'end_time' => '20:00:00',
                'day_of_week' => '火曜日',
                'status' => true,
                'note' => null,
            ],
            [
                'store_id' => 1,
                'business_date' => '2025-04-09',
                'start_time' => '11:00:00',
                'end_time' => '20:00:00',
                'day_of_week' => '水曜日',
                'status' => true,
                'note' => null,
            ],
            [
                'store_id' => 1,
                'business_date' => '2025-04-10',
                'start_time' => null,
                'end_time' => null,
                'day_of_week' => '木曜日',
                'status' => false,
                'note' => null,
            ],
            [
                'store_id' => 1,
                'business_date' => '2025-04-11',
                'start_time' => '11:00:00',
                'end_time' => '20:00:00',
                'day_of_week' => '金曜日',
                'status' => true,
                'note' => null,
            ],
            [
                'store_id' => 1,
                'business_date' => '2025-04-12',
                'start_time' => '08:00:00',
                'end_time' => '20:00:00',
                'day_of_week' => '土曜日',
                'status' => true,
                'note' => null,
            ],
            [
                'store_id' => 1,
                'business_date' => '2025-04-13',
                'start_time' => null,
                'end_time' => null,
                'day_of_week' => '日曜日',
                'status' => false,
                'note' => null,
            ],
            [
                'store_id' => 1,
                'business_date' => '2025-04-14',
                'start_time' => '11:00:00',
                'end_time' => '20:00:00',
                'day_of_week' => '月曜日',
                'status' => true,
                'note' => null,
            ],
            [
                'store_id' => 1,
                'business_date' => '2025-04-15',
                'start_time' => '11:00:00',
                'end_time' => '20:00:00',
                'day_of_week' => '火曜日',
                'status' => true,
                'note' => null,
            ],
            [
                'store_id' => 1,
                'business_date' => '2025-04-16',
                'start_time' => '11:00:00',
                'end_time' => '20:00:00',
                'day_of_week' => '水曜日',
                'status' => true,
                'note' => null,
            ],
            [
                'store_id' => 1,
                'business_date' => '2025-04-17',
                'start_time' => null,
                'end_time' => null,
                'day_of_week' => '木曜日',
                'status' => false,
                'note' => null,
            ],
            [
                'store_id' => 1,
                'business_date' => '2025-04-18',
                'start_time' => '11:00:00',
                'end_time' => '20:00:00',
                'day_of_week' => '金曜日',
                'status' => true,
                'note' => null,
            ],
            [
                'store_id' => 1,
                'business_date' => '2025-04-19',
                'start_time' => '08:00:00',
                'end_time' => '20:00:00',
                'day_of_week' => '土曜日',
                'status' => true,
                'note' => null,
            ],
            [
                'store_id' => 1,
                'business_date' => '2025-04-20',
                'start_time' => null,
                'end_time' => null,
                'day_of_week' => '日曜日',
                'status' => false,
                'note' => null,
            ],
            [
                'store_id' => 1,
                'business_date' => '2025-04-21',
                'start_time' => '11:00:00',
                'end_time' => '20:00:00',
                'day_of_week' => '月曜日',
                'status' => true,
                'note' => null,
            ],
            [
                'store_id' => 1,
                'business_date' => '2025-04-22',
                'start_time' => '11:00:00',
                'end_time' => '20:00:00',
                'day_of_week' => '火曜日',
                'status' => true,
                'note' => null,
            ],
            [
                'store_id' => 1,
                'business_date' => '2025-04-23',
                'start_time' => '11:00:00',
                'end_time' => '20:00:00',
                'day_of_week' => '水曜日',
                'status' => true,
                'note' => null,
            ],
            [
                'store_id' => 1,
                'business_date' => '2025-04-24',
                'start_time' => null,
                'end_time' => null,
                'day_of_week' => '木曜日',
                'status' => false,
                'note' => null,
            ],
            [
                'store_id' => 1,
                'business_date' => '2025-04-25',
                'start_time' => '11:00:00',
                'end_time' => '20:00:00',
                'day_of_week' => '金曜日',
                'status' => true,
                'note' => null,
            ],
            [
                'store_id' => 1,
                'business_date' => '2025-04-26',
                'start_time' => null,
                'end_time' => null,
                'day_of_week' => '土曜日',
                'status' => false,
                'note' => null,
            ],
            [
                'store_id' => 1,
                'business_date' => '2025-04-27',
                'start_time' => null,
                'end_time' => null,
                'day_of_week' => '日曜日',
                'status' => false,
                'note' => null,
            ],
            [
                'store_id' => 1,
                'business_date' => '2025-04-28',
                'start_time' => '11:00:00',
                'end_time' => '20:00:00',
                'day_of_week' => '月曜日',
                'status' => true,
                'note' => null,
            ],
            [
                'store_id' => 1,
                'business_date' => '2025-04-29',
                'start_time' => null,
                'end_time' => null,
                'day_of_week' => '火曜日',
                'status' => false,
                'note' => null,
            ],
            [
                'store_id' => 1,
                'business_date' => '2025-04-30',
                'start_time' => null,
                'end_time' => null,
                'day_of_week' => '水曜日',
                'status' => false,
                'note' => null,
            ],
        ]);
    }
}
