export const THEMECOLORS = [
  { color: '#007bff', label: 'blue' },
  { color: '#6610f2', label: 'purple' },
  { color: '#6f42c1', label: 'indigo' },
  { color: '#e83e8c', label: 'pink' },
  { color: '#dc3545', label: 'red' },
  { color: '#fd7e14', label: 'orange' },
  { color: '#ffc107', label: 'yellow' },
  { color: '#28a745', label: 'green' },
  { color: '#20c997', label: 'teal' },
  { color: '#17a2b8', label: 'cyan' },
  { color: '#343a40', label: 'dark' },
  { color: '#6c757d', label: 'secondary' },
  { color: '#007bff', label: 'primary' },
  { color: '#6c757d', label: 'secondary' },
  { color: '#28a745', label: 'success' },
  { color: '#dc3545', label: 'danger' },
  { color: '#ffc107', label: 'warning' },
  { color: '#17a2b8', label: 'info' },
  { color: '#6f42c1', label: 'purple' },
  { color: '#343a40', label: 'dark' },
];
